  /* <![CDATA[ */
  var app_vars = {
      "base_url": "https:\/\/zutrox.link\/",
      "language": "en_US",
      "copy": "Copy",
      "copied": "Copied!",
      "user_id": null,
      "home_shortening_register": "no",
      "enable_captcha": "yes",
      "captcha_type": "recaptcha",
      "reCAPTCHA_site_key": "6LedbkkUAAAAADKGjiHPnAeRO9pANLPkb0ViwHab",
      "invisible_reCAPTCHA_site_key": "",
      "solvemedia_challenge_key": "",
      "coinhive_site_key": "",
      "coinhive_hashes": "1024",
      "captcha_short_anonymous": "1",
      "captcha_shortlink": "yes",
      "captcha_signin": "no",
      "captcha_signup": "yes",
      "captcha_forgot_password": "yes",
      "captcha_contact": "yes",
      "counter_value": "10",
      "counter_start": "load",
      "get_link": "Get Link",
      "getting_link": "Getting link...",
      "skip_ad": "Skip Ad",
      "force_disable_adblock": "1",
      "please_disable_adblock": "Please disable Adblock to proceed to the destination page.",
      "cookie_notification_bar": true,
      "cookie_message": "This website uses cookies to ensure you get the best experience on our website. <a href='https:\/\/zutrox.link\/pages\/privacy' target='_blank'><b>Learn more<\/b><\/a>",
      "cookie_button": "Got it!"
  }; /* ]]> */